# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dawid/Projects/C_C++/Aoc_2020

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dawid/Projects/C_C++/Aoc_2020

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dawid/Projects/C_C++/Aoc_2020/CMakeFiles /home/dawid/Projects/C_C++/Aoc_2020/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dawid/Projects/C_C++/Aoc_2020/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

src/boarding_Pass.o: src/boarding_Pass.cpp.o

.PHONY : src/boarding_Pass.o

# target to build an object file
src/boarding_Pass.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/boarding_Pass.cpp.o
.PHONY : src/boarding_Pass.cpp.o

src/boarding_Pass.i: src/boarding_Pass.cpp.i

.PHONY : src/boarding_Pass.i

# target to preprocess a source file
src/boarding_Pass.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/boarding_Pass.cpp.i
.PHONY : src/boarding_Pass.cpp.i

src/boarding_Pass.s: src/boarding_Pass.cpp.s

.PHONY : src/boarding_Pass.s

# target to generate assembly for a file
src/boarding_Pass.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/boarding_Pass.cpp.s
.PHONY : src/boarding_Pass.cpp.s

src/declaration.o: src/declaration.cpp.o

.PHONY : src/declaration.o

# target to build an object file
src/declaration.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/declaration.cpp.o
.PHONY : src/declaration.cpp.o

src/declaration.i: src/declaration.cpp.i

.PHONY : src/declaration.i

# target to preprocess a source file
src/declaration.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/declaration.cpp.i
.PHONY : src/declaration.cpp.i

src/declaration.s: src/declaration.cpp.s

.PHONY : src/declaration.s

# target to generate assembly for a file
src/declaration.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/declaration.cpp.s
.PHONY : src/declaration.cpp.s

src/function.o: src/function.cpp.o

.PHONY : src/function.o

# target to build an object file
src/function.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/function.cpp.o
.PHONY : src/function.cpp.o

src/function.i: src/function.cpp.i

.PHONY : src/function.i

# target to preprocess a source file
src/function.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/function.cpp.i
.PHONY : src/function.cpp.i

src/function.s: src/function.cpp.s

.PHONY : src/function.s

# target to generate assembly for a file
src/function.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/function.cpp.s
.PHONY : src/function.cpp.s

src/instructions.o: src/instructions.cpp.o

.PHONY : src/instructions.o

# target to build an object file
src/instructions.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/instructions.cpp.o
.PHONY : src/instructions.cpp.o

src/instructions.i: src/instructions.cpp.i

.PHONY : src/instructions.i

# target to preprocess a source file
src/instructions.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/instructions.cpp.i
.PHONY : src/instructions.cpp.i

src/instructions.s: src/instructions.cpp.s

.PHONY : src/instructions.s

# target to generate assembly for a file
src/instructions.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/instructions.cpp.s
.PHONY : src/instructions.cpp.s

src/passport.o: src/passport.cpp.o

.PHONY : src/passport.o

# target to build an object file
src/passport.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/passport.cpp.o
.PHONY : src/passport.cpp.o

src/passport.i: src/passport.cpp.i

.PHONY : src/passport.i

# target to preprocess a source file
src/passport.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/passport.cpp.i
.PHONY : src/passport.cpp.i

src/passport.s: src/passport.cpp.s

.PHONY : src/passport.s

# target to generate assembly for a file
src/passport.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/passport.cpp.s
.PHONY : src/passport.cpp.s

src/task.o: src/task.cpp.o

.PHONY : src/task.o

# target to build an object file
src/task.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/task.cpp.o
.PHONY : src/task.cpp.o

src/task.i: src/task.cpp.i

.PHONY : src/task.i

# target to preprocess a source file
src/task.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/task.cpp.i
.PHONY : src/task.cpp.i

src/task.s: src/task.cpp.s

.PHONY : src/task.s

# target to generate assembly for a file
src/task.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/task.cpp.s
.PHONY : src/task.cpp.s

src/task1.o: src/task1.cpp.o

.PHONY : src/task1.o

# target to build an object file
src/task1.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/task1.cpp.o
.PHONY : src/task1.cpp.o

src/task1.i: src/task1.cpp.i

.PHONY : src/task1.i

# target to preprocess a source file
src/task1.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/task1.cpp.i
.PHONY : src/task1.cpp.i

src/task1.s: src/task1.cpp.s

.PHONY : src/task1.s

# target to generate assembly for a file
src/task1.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/task1.cpp.s
.PHONY : src/task1.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/boarding_Pass.o"
	@echo "... src/boarding_Pass.i"
	@echo "... src/boarding_Pass.s"
	@echo "... src/declaration.o"
	@echo "... src/declaration.i"
	@echo "... src/declaration.s"
	@echo "... src/function.o"
	@echo "... src/function.i"
	@echo "... src/function.s"
	@echo "... src/instructions.o"
	@echo "... src/instructions.i"
	@echo "... src/instructions.s"
	@echo "... src/passport.o"
	@echo "... src/passport.i"
	@echo "... src/passport.s"
	@echo "... src/task.o"
	@echo "... src/task.i"
	@echo "... src/task.s"
	@echo "... src/task1.o"
	@echo "... src/task1.i"
	@echo "... src/task1.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

